services:
  postgres:
    image: postgres:15-alpine
    container_name: wazmeow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wazmeow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wazmeow"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: wazmeow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  dbgate:
    image: dbgate/dbgate:latest
    container_name: wazmeow-dbgate
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      CONNECTIONS: con1
      LABEL_con1: WazMeow PostgreSQL
      SERVER_con1: postgres
      USER_con1: postgres
      PASSWORD_con1: password
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
      DATABASE_con1: wazmeow
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
